s=set()

n=input("enter your numbers:-")
s.add(int(n))
n=input("enter your numbers:-")
s.add(int(n))
n=input("enter your numbers:-")
s.add(int(n))
n=input("enter your numbers:-")
s.add(int(n))
n=input("enter your numbers:-")
s.add(int(n))
n=input("enter your numbers:-")
s.add(int(n))
n=input("enter your numbers:-")
s.add(int(n))

print(s)